"""add paper trades table

Revision ID: 2f28948d104a
Revises: 57d0d6d5fc60
Create Date: 2026-08-26 10:11:25.004865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f28948d104a'
down_revision: Union[str, Sequence[str], None] = '57d0d6d5fc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_opened_at'), 'paper_trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_paper_trades_status'), 'paper_trades', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_status'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_opened_at'), table_name='paper_trades')
    op.drop_table('paper_trades')
    # ### end Alembic commands ###
