"""add capital ledger table

Revision ID: 57d0d6d5fc60
Revises: 8b564d4c8bac
Create Date: 2026-08-26 09:39:38.206138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d0d6d5fc60'
down_revision: Union[str, Sequence[str], None] = '8b564d4c8bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protected_floor_inr', sa.Float(), nullable=False),
    sa.Column('tradable_capital_inr', sa.Float(), nullable=False),
    sa.Column('reserved_capital_inr', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capital_ledger')
    # ### end Alembic commands ###
