"""initial schema

Revision ID: 8b564d4c8bac
Revises: 
Create Date: 2026-08-25 18:00:35.818365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b564d4c8bac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('today_realized_pnl', sa.Float(), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('system_healthy', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', name='uq_account_state_trade_date')
    )
    op.create_index(op.f('ix_account_state_trade_date'), 'account_state', ['trade_date'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_candle_symbol_timeframe_ts')
    )
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_check_name'), 'compliance_checks', ['check_name'], unique=False)
    op.create_index(op.f('ix_compliance_checks_created_at'), 'compliance_checks', ['created_at'], unique=False)
    op.create_table('risk_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('account_equity', sa.Float(), nullable=False),
    sa.Column('estimated_costs', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=False),
    sa.Column('max_loss_inr', sa.Float(), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_evaluations_created_at'), 'risk_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_evaluations_decision'), 'risk_evaluations', ['decision'], unique=False)
    op.create_index(op.f('ix_risk_evaluations_symbol'), 'risk_evaluations', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_evaluations_symbol'), table_name='risk_evaluations')
    op.drop_index(op.f('ix_risk_evaluations_decision'), table_name='risk_evaluations')
    op.drop_index(op.f('ix_risk_evaluations_created_at'), table_name='risk_evaluations')
    op.drop_table('risk_evaluations')
    op.drop_index(op.f('ix_compliance_checks_created_at'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_check_name'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_account_state_trade_date'), table_name='account_state')
    op.drop_table('account_state')
    # ### end Alembic commands ###
