"""add strategy column to paper trades

Revision ID: d903390e1d8e
Revises: 2f28948d104a
Create Date: 2026-08-26 11:22:39.271164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd903390e1d8e'
down_revision: Union[str, Sequence[str], None] = '2f28948d104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_trades', sa.Column('strategy', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_trades', 'strategy')
    # ### end Alembic commands ###
